// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/benchmark.dart';
import 'api/diagnostic_test.dart';
import 'api/focused_benchmark.dart';
import 'api/reference_search_engine.dart';
import 'api/search_engine.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ReferenceSearchEnginePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEnginePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RegexBenchmarkerPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarkerPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SearchEnginePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEnginePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ReferenceSearchEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    dynamic raw,
  );

  @protected
  RegexBenchmarker
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    dynamic raw,
  );

  @protected
  SearchEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  );

  @protected
  ReferenceSearchEngine
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    dynamic raw,
  );

  @protected
  RegexBenchmarker
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    dynamic raw,
  );

  @protected
  SearchEngine
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  );

  @protected
  ReferenceSearchEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    dynamic raw,
  );

  @protected
  SearchEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  );

  @protected
  Map<String, Map<String, bool>>
  dco_decode_Map_String_Map_String_bool_None_None(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw);

  @protected
  Map<String, int> dco_decode_Map_String_u_32_None(dynamic raw);

  @protected
  Map<int, List<String>> dco_decode_Map_u_32_list_String_None(dynamic raw);

  @protected
  ReferenceSearchEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    dynamic raw,
  );

  @protected
  RegexBenchmarker
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    dynamic raw,
  );

  @protected
  SearchEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<SearchResult>>
  dco_decode_StreamSink_list_search_result_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BenchmarkResult dco_decode_benchmark_result(dynamic raw);

  @protected
  BenchmarkSuite dco_decode_benchmark_suite(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BenchmarkResult dco_decode_box_autoadd_benchmark_result(dynamic raw);

  @protected
  HighlightConfig dco_decode_box_autoadd_highlight_config(dynamic raw);

  @protected
  SearchResult dco_decode_box_autoadd_search_result(dynamic raw);

  @protected
  DocumentInput dco_decode_document_input(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FacetCount dco_decode_facet_count(dynamic raw);

  @protected
  HighlightConfig dco_decode_highlight_config(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BenchmarkResult> dco_decode_list_benchmark_result(dynamic raw);

  @protected
  List<DocumentInput> dco_decode_list_document_input(dynamic raw);

  @protected
  List<FacetCount> dco_decode_list_facet_count(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw);

  @protected
  List<(String, Map<String, bool>)>
  dco_decode_list_record_string_map_string_bool_none(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<(String, int)> dco_decode_list_record_string_u_32(dynamic raw);

  @protected
  List<(int, List<String>)> dco_decode_list_record_u_32_list_string(
    dynamic raw,
  );

  @protected
  List<ReferenceDocumentInput> dco_decode_list_reference_document_input(
    dynamic raw,
  );

  @protected
  List<ReferenceSearchResult> dco_decode_list_reference_search_result(
    dynamic raw,
  );

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  List<TestCase> dco_decode_list_test_case(dynamic raw);

  @protected
  BenchmarkResult? dco_decode_opt_box_autoadd_benchmark_result(dynamic raw);

  @protected
  HighlightConfig? dco_decode_opt_box_autoadd_highlight_config(dynamic raw);

  @protected
  SearchResult? dco_decode_opt_box_autoadd_search_result(dynamic raw);

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw);

  @protected
  (String, Map<String, bool>) dco_decode_record_string_map_string_bool_none(
    dynamic raw,
  );

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (String, int) dco_decode_record_string_u_32(dynamic raw);

  @protected
  (int, List<String>) dco_decode_record_u_32_list_string(dynamic raw);

  @protected
  ReferenceDocumentInput dco_decode_reference_document_input(dynamic raw);

  @protected
  ReferenceSearchResult dco_decode_reference_search_result(dynamic raw);

  @protected
  ResultsOrder dco_decode_results_order(dynamic raw);

  @protected
  SearchPageResult dco_decode_search_page_result(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  TestCase dco_decode_test_case(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ReferenceSearchEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  RegexBenchmarker
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    SseDeserializer deserializer,
  );

  @protected
  SearchEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceSearchEngine
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  RegexBenchmarker
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    SseDeserializer deserializer,
  );

  @protected
  SearchEngine
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceSearchEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  SearchEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, Map<String, bool>>
  sse_decode_Map_String_Map_String_bool_None_None(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, bool> sse_decode_Map_String_bool_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, int> sse_decode_Map_String_u_32_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, List<String>> sse_decode_Map_u_32_list_String_None(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceSearchEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  RegexBenchmarker
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    SseDeserializer deserializer,
  );

  @protected
  SearchEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<SearchResult>>
  sse_decode_StreamSink_list_search_result_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BenchmarkResult sse_decode_benchmark_result(SseDeserializer deserializer);

  @protected
  BenchmarkSuite sse_decode_benchmark_suite(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BenchmarkResult sse_decode_box_autoadd_benchmark_result(
    SseDeserializer deserializer,
  );

  @protected
  HighlightConfig sse_decode_box_autoadd_highlight_config(
    SseDeserializer deserializer,
  );

  @protected
  SearchResult sse_decode_box_autoadd_search_result(
    SseDeserializer deserializer,
  );

  @protected
  DocumentInput sse_decode_document_input(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FacetCount sse_decode_facet_count(SseDeserializer deserializer);

  @protected
  HighlightConfig sse_decode_highlight_config(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BenchmarkResult> sse_decode_list_benchmark_result(
    SseDeserializer deserializer,
  );

  @protected
  List<DocumentInput> sse_decode_list_document_input(
    SseDeserializer deserializer,
  );

  @protected
  List<FacetCount> sse_decode_list_facet_count(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, Map<String, bool>)>
  sse_decode_list_record_string_map_string_bool_none(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, int)> sse_decode_list_record_string_u_32(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, List<String>)> sse_decode_list_record_u_32_list_string(
    SseDeserializer deserializer,
  );

  @protected
  List<ReferenceDocumentInput> sse_decode_list_reference_document_input(
    SseDeserializer deserializer,
  );

  @protected
  List<ReferenceSearchResult> sse_decode_list_reference_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<TestCase> sse_decode_list_test_case(SseDeserializer deserializer);

  @protected
  BenchmarkResult? sse_decode_opt_box_autoadd_benchmark_result(
    SseDeserializer deserializer,
  );

  @protected
  HighlightConfig? sse_decode_opt_box_autoadd_highlight_config(
    SseDeserializer deserializer,
  );

  @protected
  SearchResult? sse_decode_opt_box_autoadd_search_result(
    SseDeserializer deserializer,
  );

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer);

  @protected
  (String, Map<String, bool>) sse_decode_record_string_map_string_bool_none(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, int) sse_decode_record_string_u_32(SseDeserializer deserializer);

  @protected
  (int, List<String>) sse_decode_record_u_32_list_string(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceDocumentInput sse_decode_reference_document_input(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceSearchResult sse_decode_reference_search_result(
    SseDeserializer deserializer,
  );

  @protected
  ResultsOrder sse_decode_results_order(SseDeserializer deserializer);

  @protected
  SearchPageResult sse_decode_search_page_result(SseDeserializer deserializer);

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  TestCase sse_decode_test_case(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    ReferenceSearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    RegexBenchmarker self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    ReferenceSearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    RegexBenchmarker self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    ReferenceSearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_Map_String_bool_None_None(
    Map<String, Map<String, bool>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_bool_None(
    Map<String, bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_u_32_None(
    Map<String, int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_list_String_None(
    Map<int, List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    ReferenceSearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    RegexBenchmarker self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_search_result_Sse(
    RustStreamSink<List<SearchResult>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_benchmark_result(
    BenchmarkResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_benchmark_suite(
    BenchmarkSuite self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_benchmark_result(
    BenchmarkResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_highlight_config(
    HighlightConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_result(
    SearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_document_input(DocumentInput self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_facet_count(FacetCount self, SseSerializer serializer);

  @protected
  void sse_encode_highlight_config(
    HighlightConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_benchmark_result(
    List<BenchmarkResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_document_input(
    List<DocumentInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_facet_count(
    List<FacetCount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_bool(
    List<(String, bool)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_map_string_bool_none(
    List<(String, Map<String, bool>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_u_32(
    List<(String, int)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_list_string(
    List<(int, List<String>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reference_document_input(
    List<ReferenceDocumentInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reference_search_result(
    List<ReferenceSearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_test_case(List<TestCase> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_benchmark_result(
    BenchmarkResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_highlight_config(
    HighlightConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_search_result(
    SearchResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_bool(
    (String, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_map_string_bool_none(
    (String, Map<String, bool>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_u_32(
    (String, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_list_string(
    (int, List<String>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reference_document_input(
    ReferenceDocumentInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reference_search_result(
    ReferenceSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_results_order(ResultsOrder self, SseSerializer serializer);

  @protected
  void sse_encode_search_page_result(
    SearchPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_test_case(TestCase self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_otzaria_search_engine_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_otzaria_search_engine_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEngine =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReferenceSearchEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarkerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_otzaria_search_engine_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarkerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarkerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_otzaria_search_engine_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarkerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_otzaria_search_engine_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_otzaria_search_engine_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
