// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/search_engine.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1397760606;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'search_engine',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSearchEngineSearchEngineAddDocument({
    required SearchEngine that,
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  });

  Future<void> crateApiSearchEngineSearchEngineAddDocumentsBatch({
    required SearchEngine that,
    required List<DocumentInput> docs,
  });

  Future<void> crateApiSearchEngineSearchEngineClear({
    required SearchEngine that,
  });

  Future<void> crateApiSearchEngineSearchEngineCommit({
    required SearchEngine that,
  });

  Future<int> crateApiSearchEngineSearchEngineCount({
    required SearchEngine that,
    required String query,
    required List<String> facets,
  });

  Future<Map<String, int>> crateApiSearchEngineSearchEngineCountByBook({
    required SearchEngine that,
    required String query,
    required List<String> facets,
  });

  Future<void> crateApiSearchEngineSearchEngineDeleteDocumentById({
    required SearchEngine that,
    required BigInt id,
  });

  Future<SearchResult?> crateApiSearchEngineSearchEngineGetDocumentById({
    required SearchEngine that,
    required BigInt id,
  });

  Future<BigInt> crateApiSearchEngineSearchEngineGetDocumentCount({
    required SearchEngine that,
  });

  Future<List<FacetCount>> crateApiSearchEngineSearchEngineGetFacetCounts({
    required SearchEngine that,
    required String query,
    required List<String> facets,
    required String facetPrefix,
  });

  Future<int> crateApiSearchEngineSearchEngineGetSegmentCount({
    required SearchEngine that,
  });

  SearchEngine crateApiSearchEngineSearchEngineNew({required String path});

  Future<void> crateApiSearchEngineSearchEngineOptimize({
    required SearchEngine that,
  });

  Future<void> crateApiSearchEngineSearchEngineRemoveDocumentsByTitle({
    required SearchEngine that,
    required String title,
  });

  Future<void> crateApiSearchEngineSearchEngineRollback({
    required SearchEngine that,
  });

  Future<List<SearchResult>> crateApiSearchEngineSearchEngineSearch({
    required SearchEngine that,
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
  });

  Future<SearchPageResult> crateApiSearchEngineSearchEngineSearchAndCount({
    required SearchEngine that,
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
  });

  Stream<List<SearchResult>> crateApiSearchEngineSearchEngineSearchStream({
    required SearchEngine that,
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
    required int chunkSize,
  });

  Future<void> crateApiSearchEngineSearchEngineUpsertDocument({
    required SearchEngine that,
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  });

  Future<void> crateApiSearchEngineSearchEngineUpsertDocumentsBatch({
    required SearchEngine that,
    required List<DocumentInput> docs,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SearchEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SearchEngine;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SearchEnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSearchEngineSearchEngineAddDocument({
    required SearchEngine that,
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_u_64(id, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(reference, serializer);
          sse_encode_String(topics, serializer);
          sse_encode_String(text, serializer);
          sse_encode_u_64(segment, serializer);
          sse_encode_bool(isPdf, serializer);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineAddDocumentConstMeta,
        argValues: [
          that,
          id,
          title,
          reference,
          topics,
          text,
          segment,
          isPdf,
          filePath,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineAddDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_add_document",
        argNames: [
          "that",
          "id",
          "title",
          "reference",
          "topics",
          "text",
          "segment",
          "isPdf",
          "filePath",
        ],
      );

  @override
  Future<void> crateApiSearchEngineSearchEngineAddDocumentsBatch({
    required SearchEngine that,
    required List<DocumentInput> docs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_list_document_input(docs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineAddDocumentsBatchConstMeta,
        argValues: [that, docs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSearchEngineSearchEngineAddDocumentsBatchConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_add_documents_batch",
        argNames: ["that", "docs"],
      );

  @override
  Future<void> crateApiSearchEngineSearchEngineClear({
    required SearchEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineClearConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineClearConstMeta =>
      const TaskConstMeta(debugName: "SearchEngine_clear", argNames: ["that"]);

  @override
  Future<void> crateApiSearchEngineSearchEngineCommit({
    required SearchEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineCommitConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineCommitConstMeta =>
      const TaskConstMeta(debugName: "SearchEngine_commit", argNames: ["that"]);

  @override
  Future<int> crateApiSearchEngineSearchEngineCount({
    required SearchEngine that,
    required String query,
    required List<String> facets,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          sse_encode_list_String(facets, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineCountConstMeta,
        argValues: [that, query, facets],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineCountConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_count",
        argNames: ["that", "query", "facets"],
      );

  @override
  Future<Map<String, int>> crateApiSearchEngineSearchEngineCountByBook({
    required SearchEngine that,
    required String query,
    required List<String> facets,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          sse_encode_list_String(facets, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_String_u_32_None,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineCountByBookConstMeta,
        argValues: [that, query, facets],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineCountByBookConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_count_by_book",
        argNames: ["that", "query", "facets"],
      );

  @override
  Future<void> crateApiSearchEngineSearchEngineDeleteDocumentById({
    required SearchEngine that,
    required BigInt id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_u_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineDeleteDocumentByIdConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSearchEngineSearchEngineDeleteDocumentByIdConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_delete_document_by_id",
        argNames: ["that", "id"],
      );

  @override
  Future<SearchResult?> crateApiSearchEngineSearchEngineGetDocumentById({
    required SearchEngine that,
    required BigInt id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_u_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineGetDocumentByIdConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineGetDocumentByIdConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_get_document_by_id",
        argNames: ["that", "id"],
      );

  @override
  Future<BigInt> crateApiSearchEngineSearchEngineGetDocumentCount({
    required SearchEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineGetDocumentCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSearchEngineSearchEngineGetDocumentCountConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_get_document_count",
        argNames: ["that"],
      );

  @override
  Future<List<FacetCount>> crateApiSearchEngineSearchEngineGetFacetCounts({
    required SearchEngine that,
    required String query,
    required List<String> facets,
    required String facetPrefix,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          sse_encode_list_String(facets, serializer);
          sse_encode_String(facetPrefix, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_facet_count,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineGetFacetCountsConstMeta,
        argValues: [that, query, facets, facetPrefix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineGetFacetCountsConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_get_facet_counts",
        argNames: ["that", "query", "facets", "facetPrefix"],
      );

  @override
  Future<int> crateApiSearchEngineSearchEngineGetSegmentCount({
    required SearchEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineGetSegmentCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineGetSegmentCountConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_get_segment_count",
        argNames: ["that"],
      );

  @override
  SearchEngine crateApiSearchEngineSearchEngineNew({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineNewConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineNewConstMeta =>
      const TaskConstMeta(debugName: "SearchEngine_new", argNames: ["path"]);

  @override
  Future<void> crateApiSearchEngineSearchEngineOptimize({
    required SearchEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineOptimizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineOptimizeConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_optimize",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSearchEngineSearchEngineRemoveDocumentsByTitle({
    required SearchEngine that,
    required String title,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_String(title, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiSearchEngineSearchEngineRemoveDocumentsByTitleConstMeta,
        argValues: [that, title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSearchEngineSearchEngineRemoveDocumentsByTitleConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_remove_documents_by_title",
        argNames: ["that", "title"],
      );

  @override
  Future<void> crateApiSearchEngineSearchEngineRollback({
    required SearchEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineRollbackConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineRollbackConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_rollback",
        argNames: ["that"],
      );

  @override
  Future<List<SearchResult>> crateApiSearchEngineSearchEngineSearch({
    required SearchEngine that,
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          sse_encode_list_String(facets, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_u_32(offset, serializer);
          sse_encode_results_order(order, serializer);
          sse_encode_opt_box_autoadd_highlight_config(highlight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineSearchConstMeta,
        argValues: [that, query, facets, limit, offset, order, highlight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineSearchConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_search",
        argNames: [
          "that",
          "query",
          "facets",
          "limit",
          "offset",
          "order",
          "highlight",
        ],
      );

  @override
  Future<SearchPageResult> crateApiSearchEngineSearchEngineSearchAndCount({
    required SearchEngine that,
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          sse_encode_list_String(facets, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_u_32(offset, serializer);
          sse_encode_results_order(order, serializer);
          sse_encode_opt_box_autoadd_highlight_config(highlight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_search_page_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineSearchAndCountConstMeta,
        argValues: [that, query, facets, limit, offset, order, highlight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineSearchAndCountConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_search_and_count",
        argNames: [
          "that",
          "query",
          "facets",
          "limit",
          "offset",
          "order",
          "highlight",
        ],
      );

  @override
  Stream<List<SearchResult>> crateApiSearchEngineSearchEngineSearchStream({
    required SearchEngine that,
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
    required int chunkSize,
  }) {
    final sink = RustStreamSink<List<SearchResult>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
              that,
              serializer,
            );
            sse_encode_String(query, serializer);
            sse_encode_list_String(facets, serializer);
            sse_encode_u_32(limit, serializer);
            sse_encode_u_32(offset, serializer);
            sse_encode_results_order(order, serializer);
            sse_encode_opt_box_autoadd_highlight_config(highlight, serializer);
            sse_encode_u_32(chunkSize, serializer);
            sse_encode_StreamSink_list_search_result_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSearchEngineSearchEngineSearchStreamConstMeta,
          argValues: [
            that,
            query,
            facets,
            limit,
            offset,
            order,
            highlight,
            chunkSize,
            sink,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineSearchStreamConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_search_stream",
        argNames: [
          "that",
          "query",
          "facets",
          "limit",
          "offset",
          "order",
          "highlight",
          "chunkSize",
          "sink",
        ],
      );

  @override
  Future<void> crateApiSearchEngineSearchEngineUpsertDocument({
    required SearchEngine that,
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_u_64(id, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(reference, serializer);
          sse_encode_String(topics, serializer);
          sse_encode_String(text, serializer);
          sse_encode_u_64(segment, serializer);
          sse_encode_bool(isPdf, serializer);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchEngineSearchEngineUpsertDocumentConstMeta,
        argValues: [
          that,
          id,
          title,
          reference,
          topics,
          text,
          segment,
          isPdf,
          filePath,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchEngineSearchEngineUpsertDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_upsert_document",
        argNames: [
          "that",
          "id",
          "title",
          "reference",
          "topics",
          "text",
          "segment",
          "isPdf",
          "filePath",
        ],
      );

  @override
  Future<void> crateApiSearchEngineSearchEngineUpsertDocumentsBatch({
    required SearchEngine that,
    required List<DocumentInput> docs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
            that,
            serializer,
          );
          sse_encode_list_document_input(docs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiSearchEngineSearchEngineUpsertDocumentsBatchConstMeta,
        argValues: [that, docs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSearchEngineSearchEngineUpsertDocumentsBatchConstMeta =>
      const TaskConstMeta(
        debugName: "SearchEngine_upsert_documents_batch",
        argNames: ["that", "docs"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SearchEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SearchEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  SearchEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SearchEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SearchEngine
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SearchEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SearchEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SearchEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, int> dco_decode_Map_String_u_32_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_u_32(raw).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  SearchEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SearchEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<List<SearchResult>>
  dco_decode_StreamSink_list_search_result_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  HighlightConfig dco_decode_box_autoadd_highlight_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_highlight_config(raw);
  }

  @protected
  SearchResult dco_decode_box_autoadd_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_search_result(raw);
  }

  @protected
  DocumentInput dco_decode_document_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return DocumentInput(
      id: dco_decode_u_64(arr[0]),
      title: dco_decode_String(arr[1]),
      reference: dco_decode_String(arr[2]),
      topics: dco_decode_String(arr[3]),
      text: dco_decode_String(arr[4]),
      segment: dco_decode_u_64(arr[5]),
      isPdf: dco_decode_bool(arr[6]),
      filePath: dco_decode_String(arr[7]),
    );
  }

  @protected
  FacetCount dco_decode_facet_count(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FacetCount(
      path: dco_decode_String(arr[0]),
      count: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  HighlightConfig dco_decode_highlight_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HighlightConfig(
      highlightPrefix: dco_decode_String(arr[0]),
      highlightPostfix: dco_decode_String(arr[1]),
      maxChars: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DocumentInput> dco_decode_list_document_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_document_input).toList();
  }

  @protected
  List<FacetCount> dco_decode_list_facet_count(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_facet_count).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, int)> dco_decode_list_record_string_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_u_32).toList();
  }

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_result).toList();
  }

  @protected
  HighlightConfig? dco_decode_opt_box_autoadd_highlight_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_highlight_config(raw);
  }

  @protected
  SearchResult? dco_decode_opt_box_autoadd_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_search_result(raw);
  }

  @protected
  (String, int) dco_decode_record_string_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_u_32(arr[1]));
  }

  @protected
  ResultsOrder dco_decode_results_order(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ResultsOrder.values[raw as int];
  }

  @protected
  SearchPageResult dco_decode_search_page_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SearchPageResult(
      totalCount: dco_decode_u_32(arr[0]),
      results: dco_decode_list_search_result(arr[1]),
    );
  }

  @protected
  SearchResult dco_decode_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SearchResult(
      title: dco_decode_String(arr[0]),
      reference: dco_decode_String(arr[1]),
      text: dco_decode_String(arr[2]),
      id: dco_decode_u_64(arr[3]),
      segment: dco_decode_u_64(arr[4]),
      isPdf: dco_decode_bool(arr[5]),
      filePath: dco_decode_String(arr[6]),
      score: dco_decode_u_32(arr[7]),
      wordDistance: dco_decode_u_32(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  SearchEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SearchEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SearchEngine
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SearchEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SearchEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SearchEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Map<String, int> sse_decode_Map_String_u_32_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_u_32(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  SearchEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SearchEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<List<SearchResult>>
  sse_decode_StreamSink_list_search_result_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  HighlightConfig sse_decode_box_autoadd_highlight_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_highlight_config(deserializer));
  }

  @protected
  SearchResult sse_decode_box_autoadd_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_search_result(deserializer));
  }

  @protected
  DocumentInput sse_decode_document_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_reference = sse_decode_String(deserializer);
    var var_topics = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_segment = sse_decode_u_64(deserializer);
    var var_isPdf = sse_decode_bool(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    return DocumentInput(
      id: var_id,
      title: var_title,
      reference: var_reference,
      topics: var_topics,
      text: var_text,
      segment: var_segment,
      isPdf: var_isPdf,
      filePath: var_filePath,
    );
  }

  @protected
  FacetCount sse_decode_facet_count(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_count = sse_decode_u_64(deserializer);
    return FacetCount(path: var_path, count: var_count);
  }

  @protected
  HighlightConfig sse_decode_highlight_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_highlightPrefix = sse_decode_String(deserializer);
    var var_highlightPostfix = sse_decode_String(deserializer);
    var var_maxChars = sse_decode_u_32(deserializer);
    return HighlightConfig(
      highlightPrefix: var_highlightPrefix,
      highlightPostfix: var_highlightPostfix,
      maxChars: var_maxChars,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DocumentInput> sse_decode_list_document_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DocumentInput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_document_input(deserializer));
    }
    return ans_;
  }

  @protected
  List<FacetCount> sse_decode_list_facet_count(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FacetCount>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_facet_count(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, int)> sse_decode_list_record_string_u_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, int)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_u_32(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_result(deserializer));
    }
    return ans_;
  }

  @protected
  HighlightConfig? sse_decode_opt_box_autoadd_highlight_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_highlight_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SearchResult? sse_decode_opt_box_autoadd_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_search_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, int) sse_decode_record_string_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_u_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  ResultsOrder sse_decode_results_order(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ResultsOrder.values[inner];
  }

  @protected
  SearchPageResult sse_decode_search_page_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalCount = sse_decode_u_32(deserializer);
    var var_results = sse_decode_list_search_result(deserializer);
    return SearchPageResult(totalCount: var_totalCount, results: var_results);
  }

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_reference = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_id = sse_decode_u_64(deserializer);
    var var_segment = sse_decode_u_64(deserializer);
    var var_isPdf = sse_decode_bool(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_score = sse_decode_u_32(deserializer);
    var var_wordDistance = sse_decode_u_32(deserializer);
    return SearchResult(
      title: var_title,
      reference: var_reference,
      text: var_text,
      id: var_id,
      segment: var_segment,
      isPdf: var_isPdf,
      filePath: var_filePath,
      score: var_score,
      wordDistance: var_wordDistance,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SearchEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SearchEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SearchEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_u_32_None(
    Map<String, int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_u_32(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SearchEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_search_result_Sse(
    RustStreamSink<List<SearchResult>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_highlight_config(
    HighlightConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_highlight_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_search_result(
    SearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_search_result(self, serializer);
  }

  @protected
  void sse_encode_document_input(DocumentInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.reference, serializer);
    sse_encode_String(self.topics, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_u_64(self.segment, serializer);
    sse_encode_bool(self.isPdf, serializer);
    sse_encode_String(self.filePath, serializer);
  }

  @protected
  void sse_encode_facet_count(FacetCount self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.count, serializer);
  }

  @protected
  void sse_encode_highlight_config(
    HighlightConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.highlightPrefix, serializer);
    sse_encode_String(self.highlightPostfix, serializer);
    sse_encode_u_32(self.maxChars, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_document_input(
    List<DocumentInput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_document_input(item, serializer);
    }
  }

  @protected
  void sse_encode_list_facet_count(
    List<FacetCount> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_facet_count(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_u_32(
    List<(String, int)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_u_32(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_result(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_highlight_config(
    HighlightConfig? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_highlight_config(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_search_result(
    SearchResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_search_result(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_u_32(
    (String, int) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_u_32(self.$2, serializer);
  }

  @protected
  void sse_encode_results_order(ResultsOrder self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_search_page_result(
    SearchPageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.totalCount, serializer);
    sse_encode_list_search_result(self.results, serializer);
  }

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.reference, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_u_64(self.id, serializer);
    sse_encode_u_64(self.segment, serializer);
    sse_encode_bool(self.isPdf, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_u_32(self.score, serializer);
    sse_encode_u_32(self.wordDistance, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class SearchEngineImpl extends RustOpaque implements SearchEngine {
  // Not to be used by end users
  SearchEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SearchEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SearchEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SearchEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SearchEnginePtr,
  );

  Future<void> addDocument({
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  }) => RustLib.instance.api.crateApiSearchEngineSearchEngineAddDocument(
    that: this,
    id: id,
    title: title,
    reference: reference,
    topics: topics,
    text: text,
    segment: segment,
    isPdf: isPdf,
    filePath: filePath,
  );

  Future<void> addDocumentsBatch({required List<DocumentInput> docs}) =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineAddDocumentsBatch(
        that: this,
        docs: docs,
      );

  Future<void> clear() =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineClear(that: this);

  Future<void> commit() =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineCommit(that: this);

  Future<int> count({required String query, required List<String> facets}) =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineCount(
        that: this,
        query: query,
        facets: facets,
      );

  Future<Map<String, int>> countByBook({
    required String query,
    required List<String> facets,
  }) => RustLib.instance.api.crateApiSearchEngineSearchEngineCountByBook(
    that: this,
    query: query,
    facets: facets,
  );

  Future<void> deleteDocumentById({required BigInt id}) => RustLib.instance.api
      .crateApiSearchEngineSearchEngineDeleteDocumentById(that: this, id: id);

  Future<SearchResult?> getDocumentById({required BigInt id}) => RustLib
      .instance
      .api
      .crateApiSearchEngineSearchEngineGetDocumentById(that: this, id: id);

  Future<BigInt> getDocumentCount() => RustLib.instance.api
      .crateApiSearchEngineSearchEngineGetDocumentCount(that: this);

  Future<List<FacetCount>> getFacetCounts({
    required String query,
    required List<String> facets,
    required String facetPrefix,
  }) => RustLib.instance.api.crateApiSearchEngineSearchEngineGetFacetCounts(
    that: this,
    query: query,
    facets: facets,
    facetPrefix: facetPrefix,
  );

  Future<int> getSegmentCount() => RustLib.instance.api
      .crateApiSearchEngineSearchEngineGetSegmentCount(that: this);

  Future<void> optimize() =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineOptimize(that: this);

  Future<void> removeDocumentsByTitle({required String title}) => RustLib
      .instance
      .api
      .crateApiSearchEngineSearchEngineRemoveDocumentsByTitle(
        that: this,
        title: title,
      );

  Future<void> rollback() =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineRollback(that: this);

  Future<List<SearchResult>> search({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
  }) => RustLib.instance.api.crateApiSearchEngineSearchEngineSearch(
    that: this,
    query: query,
    facets: facets,
    limit: limit,
    offset: offset,
    order: order,
    highlight: highlight,
  );

  Future<SearchPageResult> searchAndCount({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
  }) => RustLib.instance.api.crateApiSearchEngineSearchEngineSearchAndCount(
    that: this,
    query: query,
    facets: facets,
    limit: limit,
    offset: offset,
    order: order,
    highlight: highlight,
  );

  Stream<List<SearchResult>> searchStream({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
    required int chunkSize,
  }) => RustLib.instance.api.crateApiSearchEngineSearchEngineSearchStream(
    that: this,
    query: query,
    facets: facets,
    limit: limit,
    offset: offset,
    order: order,
    highlight: highlight,
    chunkSize: chunkSize,
  );

  Future<void> upsertDocument({
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  }) => RustLib.instance.api.crateApiSearchEngineSearchEngineUpsertDocument(
    that: this,
    id: id,
    title: title,
    reference: reference,
    topics: topics,
    text: text,
    segment: segment,
    isPdf: isPdf,
    filePath: filePath,
  );

  Future<void> upsertDocumentsBatch({required List<DocumentInput> docs}) =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineUpsertDocumentsBatch(
        that: this,
        docs: docs,
      );
}
