// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `all_fields`, `build_fts_query_stateless`, `build_fts_query`, `build_results`, `collect_addresses`, `default`, `ensure_writer`, `expand_alternative`, `expand_group`, `open_writer_no_merge`, `open_writer`, `optimize_committed_segments`, `restore_writer`, `take_writer`, `writer_mut`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BookCountCollector`, `BookCountSegmentCollector`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `collect`, `for_segment`, `harvest`, `merge_fruits`, `requires_scoring`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SearchEngine>>
abstract class SearchEngine implements RustOpaqueInterface {
  Future<void> addDocument({
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  });

  Future<void> addDocumentsBatch({required List<DocumentInput> docs});

  Future<void> clear();

  Future<void> commit();

  Future<int> count({required String query, required List<String> facets});

  Future<Map<String, int>> countByBook({
    required String query,
    required List<String> facets,
  });

  Future<void> deleteDocumentById({required BigInt id});

  Future<SearchResult?> getDocumentById({required BigInt id});

  Future<BigInt> getDocumentCount();

  Future<List<FacetCount>> getFacetCounts({
    required String query,
    required List<String> facets,
    required String facetPrefix,
  });

  Future<int> getSegmentCount();

  factory SearchEngine({required String path}) =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineNew(path: path);

  Future<void> optimize();

  Future<void> removeDocumentsByTitle({required String title});

  Future<void> rollback();

  Future<List<SearchResult>> search({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
  });

  Future<SearchPageResult> searchAndCount({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
  });

  Stream<List<SearchResult>> searchStream({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    HighlightConfig? highlight,
    required int chunkSize,
  });

  Future<void> upsertDocument({
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  });

  Future<void> upsertDocumentsBatch({required List<DocumentInput> docs});
}

class DocumentInput {
  final BigInt id;
  final String title;
  final String reference;
  final String topics;
  final String text;
  final BigInt segment;
  final bool isPdf;
  final String filePath;

  const DocumentInput({
    required this.id,
    required this.title,
    required this.reference,
    required this.topics,
    required this.text,
    required this.segment,
    required this.isPdf,
    required this.filePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      reference.hashCode ^
      topics.hashCode ^
      text.hashCode ^
      segment.hashCode ^
      isPdf.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          reference == other.reference &&
          topics == other.topics &&
          text == other.text &&
          segment == other.segment &&
          isPdf == other.isPdf &&
          filePath == other.filePath;
}

class FacetCount {
  final String path;
  final BigInt count;

  const FacetCount({required this.path, required this.count});

  @override
  int get hashCode => path.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FacetCount &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          count == other.count;
}

class HighlightConfig {
  final String highlightPrefix;
  final String highlightPostfix;
  final int maxChars;

  const HighlightConfig({
    required this.highlightPrefix,
    required this.highlightPostfix,
    required this.maxChars,
  });

  @override
  int get hashCode =>
      highlightPrefix.hashCode ^ highlightPostfix.hashCode ^ maxChars.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightConfig &&
          runtimeType == other.runtimeType &&
          highlightPrefix == other.highlightPrefix &&
          highlightPostfix == other.highlightPostfix &&
          maxChars == other.maxChars;
}

enum ResultsOrder { catalogue, relevance }

class SearchPageResult {
  final int totalCount;
  final List<SearchResult> results;

  const SearchPageResult({required this.totalCount, required this.results});

  @override
  int get hashCode => totalCount.hashCode ^ results.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchPageResult &&
          runtimeType == other.runtimeType &&
          totalCount == other.totalCount &&
          results == other.results;
}

class SearchResult {
  final String title;
  final String reference;
  final String text;
  final BigInt id;
  final BigInt segment;
  final bool isPdf;
  final String filePath;
  final int score;
  final int wordDistance;

  const SearchResult({
    required this.title,
    required this.reference,
    required this.text,
    required this.id,
    required this.segment,
    required this.isPdf,
    required this.filePath,
    required this.score,
    required this.wordDistance,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      reference.hashCode ^
      text.hashCode ^
      id.hashCode ^
      segment.hashCode ^
      isPdf.hashCode ^
      filePath.hashCode ^
      score.hashCode ^
      wordDistance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          reference == other.reference &&
          text == other.text &&
          id == other.id &&
          segment == other.segment &&
          isPdf == other.isPdf &&
          filePath == other.filePath &&
          score == other.score &&
          wordDistance == other.wordDistance;
}
